---
title: "ShahRProjectPt2"
author: "Priyanshi Shah"
date: "2023-03-04"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(readr)
library(tibble)
library(picante)
library(nlme)

```


```{r}
comm <- read.csv("grassland.community.csv", header = TRUE, row.names = 1) 

class(comm)

dim(comm)

rownames(comm)

head(colnames(comm))

comm[1:5, 1:5]

apply(comm, 1, sum) #checking total abundance in each sample

comm <- decostand(comm, method = "total")

apply(comm, 1, sum)

comm[1:5, 1:5]

```
```{r}

traits <- read.csv("species.traits.csv", header = TRUE, row.names = 1)
# take a peek at the data
head(traits)

pairs(traits)

traits <- log10(traits) #log transform all variables

pairs(traits)
```
```{r}

# replace filename
metadata <- read.csv("plot.metadata.csv", header = TRUE, row.names = 1)
# take a peek at the data
head(metadata)
```
```{r}

phy <- read.tree("grassland.phylogeny.newick")
class(phy)

phy

names(phy)

phy$tip.label[1:5]

Ntip(phy)

plot(phy, cex = 0.5)
```
```{r}
ls()

```
```{r}

# check for mismatches/missing species
combined <- match.phylo.comm(phy, comm)
# the resulting object is a list with $phy and $comm elements.  replace our
# original data with the sorted/matched data
phy <- combined$phy
comm <- combined$comm

combined <- match.phylo.data(phy, traits)
# the resulting object is a list with $phy and $data elements.  replace our
# original data with the sorted/matched data
phy <- combined$phy
traits <- combined$data

all.equal(rownames(comm), rownames(metadata))


# they all match - if they didn't we could sort them to the same order sort
# metadata rows to be in the same order as community rows
metadata <- metadata[rownames(comm), ]
```



```{r}
boxplot(specnumber(comm) ~ metadata$rel.moisture, ylab = "# of species")

t.test(specnumber(comm), metadata$rel.moisture)

# plot species accumulion curve across samples
plot(specaccum(comm), xlab = "# of samples", ylab = "# of species")

# calculate Bray-Curtis distance among samples
comm.bc.dist <- vegdist(comm, method = "bray")
# cluster communities using average-linkage algorithm
comm.bc.clust <- hclust(comm.bc.dist, method = "average")
# plot cluster diagram
plot(comm.bc.clust, ylab = "Bray-Curtis dissimilarity")

# The metaMDS function automatically transforms data and checks solution
# robustness
comm.bc.mds <- metaMDS(comm, dist = "bray")

# Assess goodness of ordination fit (stress plot)
stressplot(comm.bc.mds)

# plot site scores as text
ordiplot(comm.bc.mds, display = "sites", type = "text")

# automated plotting of results - tries to eliminate overlapping labels
ordipointlabel(comm.bc.mds)

```


```{r}
# automated plotting of results - tries to eliminate overlapping labels
ordipointlabel(comm.bc.mds)

mds.fig <- ordiplot(comm.bc.mds, type = "none")
# plot just the samples, colour by moisture, pch=19 means plot a circle
points(mds.fig, "sites", pch = 19, col = "green", select = metadata$rel.moisture == 
    "Fescue")
points(mds.fig, "sites", pch = 19, col = "blue", select = metadata$rel.moisture == 
    "Mixedgrass")
# add confidence ellipses around moisture types
ordiellipse(comm.bc.mds, metadata$rel.moisture, conf = 0.95, label = TRUE)
# overlay the cluster results we calculated earlier
ordicluster(comm.bc.mds, comm.bc.clust, col = "gray")

```
```{r}
# plot Sphaeralcea abundance. cex increases the size of bubbles.

ordisurf(comm.bc.mds, comm[, "Sphaeralcea_coccinea"], bubble = TRUE, main = "Sphaeralcea coccinea abundance", 
    cex = 3)

ordiplot(comm.bc.mds)
# calculate and plot environmental variable correlations with the axes use
# the subset of metadata that are environmental data
plot(envfit(comm.bc.mds, metadata[, 3:6]))

```
```{r}
apply(traits, 2, Kcalc, phy)

# another way to do it with significance testing we have to convert the tree
# to be dichotomous before calculating P-values
multiPhylosignal(traits, multi2di(phy))

# Plot phylogeny facing upwards. Show node labels but not tip labels. cex
# shrinks labels.
plot(phy, direction = "up", show.tip.label = FALSE, show.node.label = TRUE, 
    cex = 0.7)
# Plot leaf area on the phylogeny. cex argument scales symbol size by trait
# value.
tiplabels(pch = 19, col = "black", cex = 3 * (traits[, "LeafArea"]/max(traits[, 
    "LeafArea"])))


```
```{r}

# GLS of root tissue density as a function of SRL - non-phylogenetic model
root.gls <- gls(RootTissueDens ~ SRL, data = traits)
anova(root.gls)


# Phylogenetic GLS - adds effect of phylogeny to the model
root.pgls <- gls(RootTissueDens ~ SRL, correlation = corBrownian(value = 1, 
    phy), data = traits)
anova(root.pgls)



# plot relationship
plot(RootTissueDens ~ SRL, data = traits, xlab = "SRL (specific root length)", 
    ylab = "Root tissue density")
# add model fit lines - coef is the model fit coefficients, lwd increases
# line width
abline(coef(root.gls), lwd = 2, col = "black")
abline(coef(root.pgls), lwd = 2, col = "red")
legend("bottomleft", legend = c("GLS fit", "Phylogenetic GLS fit"), lwd = 2, 
    col = c("black", "red"))

```
```{r}

# Calculate Faith's PD
comm.pd <- pd(comm, phy)
head(comm.pd)

# Plot Faith's PD by moisture
boxplot(comm.pd$PD ~ metadata$rel.moisture, xlab = "Moisture", ylab = "Faith's PD")

# Test for PD differences in moisture
t.test(comm.pd$PD, metadata$rel.moisture)


# Compare PD and species richness
plot(comm.pd$PD ~ comm.pd$SR, xlab = "Species richness", ylab = "Faith's PD")

```
```{r}
# convert phylogenety to a distance matrix
phy.dist <- cophenetic(phy)
# calculate ses.mpd
comm.sesmpd <- ses.mpd(comm, phy.dist, null.model = "richness", abundance.weighted = FALSE, 
    runs = 999)
head(comm.sesmpd)



# calculate ses.mntd
comm.sesmntd <- ses.mntd(comm, phy.dist, null.model = "richness", abundance.weighted = FALSE, 
    runs = 999)
head(comm.sesmntd)


# compare ses.mpd between different moisture
plot(comm.sesmpd$mpd.obs.z ~ metadata$rel.moisture, xlab = "Moisture", ylab = "SES(MPD)")
abline(h = 0, col = "gray")


t.test(comm.sesmpd$mpd.obs.z, metadata$rel.moisture)


# compare ses.mntd between different moisture
plot(comm.sesmntd$mntd.obs.z ~ metadata$rel.moisture, xlab = "Moisture", ylab = "SES(MNTD)")
abline(h = 0, col = "gray")

t.test(comm.sesmntd$mntd.obs.z, metadata$rel.moisture)


# plot species present in a fescue community
plot(phy, show.tip.label = FALSE, main = "Fescue community fes-K-11")
tiplabels(tip = which(phy$tip.label %in% colnames(comm)[comm["fes-K-11", ] > 
    0]), pch = 19)

# plot species present in a mixedgrass community
plot(phy, show.tip.label = FALSE, main = "Fescue community mix-H-23")
tiplabels(tip = which(phy$tip.label %in% colnames(comm)[comm["mix-H-23", ] > 
    0]), pch = 19)

```

```{r}

# calculate trait distance - Euclidean distance among scaled trait values -
# we want the full distance matrix

trait.dist <- as.matrix(dist(scale(traits), method = "euclidean"))
# calculate trait ses.mpd
comm.sesmpd.traits <- ses.mpd(comm, trait.dist, null.model = "richness", abundance.weighted = FALSE, 
    runs = 999)
# compare trait ses.mpd between different moisture
plot(comm.sesmpd.traits$mpd.obs.z ~ metadata$rel.moisture, xlab = "Moisture", ylab = "Trait SES(MPD)")
abline(h = 0, col = "gray")



# calculate phylogenetic MNTD beta diversity
comm.mntd.dist <- comdistnt(comm, phy.dist, abundance.weighted = TRUE)
# calculate functional trait MNTD beta diversity
comm.mntd.traits.dist <- comdistnt(comm, trait.dist, abundance.weighted = TRUE)
# calculate Mantel correlation for taxonomic Bray-Curtis vs. phylogenetic
# MNTD diversity
mantel(comm.bc.dist, comm.mntd.dist)



# calculate Mantel correlation for taxonomic Bray-Curtis vs. trait MNTD
# diversity
mantel(comm.bc.dist, comm.mntd.traits.dist)

```
```{r}

# NMDS ordination of phylogenetic distances - use monoMDS since we only have
# among-sample distances
comm.mntd.mds <- monoMDS(comm.mntd.dist)
# set up the plotting area but don't plot anything yet
mds.fig <- ordiplot(comm.mntd.mds, type = "none")
# plot just the samples, colour by moisture, pch=19 means plot a circle
points(mds.fig, "sites", pch = 19, col = "green", select = metadata$rel.moisture == 
    "Fescue")
points(mds.fig, "sites", pch = 19, col = "blue", select = metadata$rel.moisture == 
    "Mixedgrass")
# add confidence ellipses around moisture
ordiellipse(comm.mntd.mds, metadata$rel.moisture, conf = 0.95, label = TRUE)


# NMDS ordination of trait distances - use monoMDS since we only have
# among-sample distances
comm.mntd.traits.mds <- monoMDS(comm.mntd.traits.dist)
# set up the plotting area but don't plot anything yet
mds.fig <- ordiplot(comm.mntd.traits.mds, type = "none")
# plot just the samples, colour by moisture, pch=19 means plot a circle
points(mds.fig, "sites", pch = 19, col = "green", select = metadata$rel.moisture == 
    "Fescue")
points(mds.fig, "sites", pch = 19, col = "blue", select = metadata$rel.moisture == 
    "Mixedgrass")
# add confidence ellipses around moisture
ordiellipse(comm.mntd.traits.mds, metadata$rel.moisture, conf = 0.95, label = TRUE)



```
```{r}

adonis2(comm.bc.dist ~ rel.moisture, data = metadata)

adonis2(comm.mntd.dist ~ rel.moisture, data = metadata)


adonis2(comm.mntd.traits.dist ~ rel.moisture, data = metadata)

```

